Create Webpage and add required for website and webpage fields
Zocom-LIA/CmsHackerHeroes pull request #30
Opened 2024-09-19 08:48 UTC by MohamedDiaa

add image url

Create Webpage and add required for website and webpage fields

2024-09-19 08:59 UTC, PatrikHogblom submitted a review, later dismissed

2024-09-19 09:01 UTC, PatrikHogblom approved these changes, later dismissed

2024-09-19 15:23 UTC, jenscodejens requested changes
Registrera ny user fungerar inte.

<img width="227" alt="image" src="https://github.com/user-attachments/assets/16cca423-3453-494d-b34a-cd1be4ecc15c">

Add Page = fungerar
Details -> Web Pages -> Create New  skickar inte med websiteId
<img width="228" alt="image" src="https://github.com/user-attachments/assets/3b36dceb-e766-4a13-9b4e-8b5cdd083a96">

Patrik, Jens, Habib får felen

2024-09-20 08:12 UTC, jenscodejens approved these changes

2024-09-20 08:12 UTC, PatrikHogblom approved these changes

2024-09-20 08:13 UTC, merged