Refactor home page och navbar for non login visitors
Zocom-LIA/CmsHackerHeroes pull request #62
Opened 2024-10-09 07:55 UTC by emusat2021

Refactor home page och navbar for non login visitors

2024-10-09 09:26 UTC, hhmbow submitted a review, later dismissed

2024-10-09 12:10 UTC, hhmbow submitted a review, later dismissed

2024-10-10 08:11 UTC, PatrikHogblom commented
sidhuvud döljer rubriken döljs för någon anledning, 
![image](https://github.com/user-attachments/assets/abcbb6bc-52a9-4bad-a14b-56e5d9b45dee)
![image](https://github.com/user-attachments/assets/582dc4ee-39bb-42e4-ab98-d8ee257aaed7)
![image](https://github.com/user-attachments/assets/61f6ca9f-a3ca-4e30-889c-e01cc538a73f). 

Header bör förbättras, men i övrigt så ser hemsidan väldigt snyggt ut och är responsiv

2024-10-10 12:46 UTC, emusat2021 commented
Space added:
![image](https://github.com/user-attachments/assets/67327078-8223-4a84-8e66-e4833def443b)

![image](https://github.com/user-attachments/assets/cf1df9f8-8466-4316-8995-dafc28a6c0df)

2024-10-10 13:19 UTC, emusat2021 commented
Done below as well:
![image](https://github.com/user-attachments/assets/c6aa73de-667c-4d59-94bf-10c82084e02d)

2024-10-14 08:54 UTC, EddMal commented
Det skulle vara tydligare om rubriken kom med när en besökare trycker på ett menyval. Se exempel nedan:
(Nuvarande "Om oss" rubriken är utanför vyn)
![image](https://github.com/user-attachments/assets/3899b181-d2b2-4777-83ad-7d2499876b22)

Förslag, rubriken visas
![image](https://github.com/user-attachments/assets/7f068d6d-7dca-4119-ac56-1fa498cb66aa)

2024-10-14 08:55 UTC, jenscodejens requested changes
<img width="575" alt="image" src="https://github.com/user-attachments/assets/58513f2a-a2e7-467d-b0cd-0020a0b7e5fa">

Sparade Webbsidor & CMS (hem till vänster) i navbar borde ha den fina vita animationen med (även om den inte är dropdown).

Det är inte enhetligt att CMS är blå, Sparade Webbsidor är blå och små bokstäver och INSTÄLLNINGAR är i caps med animation.

Animationen är jättefin, jag föreslår:
- CMS - lägg till animationen 
- Sparade Webbsidor - lägg till animationen
- INSTÄLLNINGAR - gör till "Inställningar"

I princip gör så att alla ser ut som INSTÄLLNINGAR nu (och med bara första bokstaven stor)

2024-10-15 19:49 UTC, emusat2021 commented
> Det skulle vara tydligare om rubriken kom med när en besökare trycker på ett menyval. Se exempel nedan: (Nuvarande "Om oss" rubriken är utanför vyn) ![image](https://private-user-images.githubusercontent.com/107246914/376169528-3899b181-d2b2-4777-83ad-7d2499876b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTc5NjMsIm5iZiI6MTcyOTAxNzY2MywicGF0aCI6Ii8xMDcyNDY5MTQvMzc2MTY5NTI4LTM4OTliMTgxLWQyYjItNDc3Ny04M2FkLTdkMjQ5OTg3NmIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxODQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDcyMGM2MjgxN2RkNjA0NjM1M2U5YTFiYjdkMzAyODhmNTY5YmQ3ZTkzMjQ0MThiMzYyZjNmMGUxNjMwMTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UAG2KVJ9cczrE_vToEthVueeNKnTILQ69Xdax_tsNZc)
> 
> Förslag, rubriken visas ![image](https://private-user-images.githubusercontent.com/107246914/376170642-7f068d6d-7dca-4119-ac56-1fa498cb66aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTc5NjMsIm5iZiI6MTcyOTAxNzY2MywicGF0aCI6Ii8xMDcyNDY5MTQvMzc2MTcwNjQyLTdmMDY4ZDZkLTdkY2EtNDExOS1hYzU2LTFmYTQ5OGNiNjZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxODQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2Y5YzNjZTI4NWRhNjZkZGUzNjM1NWMyNDc4NmJiMTkxZjMwZDA3M2MxOGFlMWNlZjk4NGFjMDJmNjVhOTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v04wbbfqFxEojJjT889KLyJ-oeh6V-tWePPHXq2K_hc)

Done:
![image](https://github.com/user-attachments/assets/661db030-8ce7-4428-aeaa-72ae7016bee3)

2024-10-15 19:52 UTC, emusat2021 commented
> <img alt="image" width="575" src="https://private-user-images.githubusercontent.com/161465689/376169322-58513f2a-a2e7-467d-b0cd-0020a0b7e5fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTc5NjMsIm5iZiI6MTcyOTAxNzY2MywicGF0aCI6Ii8xNjE0NjU2ODkvMzc2MTY5MzIyLTU4NTEzZjJhLWEyZTctNDY3ZC1iMGNkLTAwMjBhMGI3ZTVmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxODQxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjA2ZGY5MmMwZDdiYTM5NDE0NDQ3YjEzMGRhZTk0MzFkNjBmYjAwYzFjYTNhOGJiZjM5NTZjMWRlMDkxZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s7Ne6NTQVB2Fejr88vOLfOk4zGAUR1bcp14jqSHQtK8">
> Sparade Webbsidor & CMS (hem till vänster) i navbar borde ha den fina vita animationen med (även om den inte är dropdown).
> 
> Det är inte enhetligt att CMS är blå, Sparade Webbsidor är blå och små bokstäver och INSTÄLLNINGAR är i caps med animation.
> 
> Animationen är jättefin, jag föreslår:
> 
> * CMS - lägg till animationen
> * Sparade Webbsidor - lägg till animationen
> * INSTÄLLNINGAR - gör till "Inställningar"
> 
> I princip gör så att alla ser ut som INSTÄLLNINGAR nu (och med bara första bokstaven stor)

Answer:
It will need a different feature branch for your ideas.
This feature branch will adress to home page just.

2024-10-16 07:57 UTC, jenscodejens approved these changes
Testat

2024-10-16 07:59 UTC, EddMal approved these changes

2024-10-16 08:00 UTC, merged