Update navbar  inputform user experience feature
Zocom-LIA/CmsHackerHeroes pull request #70
Opened 2024-10-22 09:59 UTC by EddMal

Navbars editng user flow changed:
![image](https://github.com/user-attachments/assets/331974b5-1b32-49c9-84ea-9ba697972d4a)

Added back arrow to the edit page points to website details:
![image](https://github.com/user-attachments/assets/c49a02ef-bd45-41b6-a708-be073974e8ce)
![image](https://github.com/user-attachments/assets/79bc1520-0203-47b6-9e42-09a2fbcdb97a)

2024-10-22 10:18 UTC, emusat2021 approved these changes, later dismissed

2024-10-22 11:33 UTC, PatrikHogblom approved these changes, later dismissed
ser bra ut, är bara lite design som kan behövas att ändras framöver

2024-10-22 12:26 UTC, hhmbow commented
Ser bra ut, men kan du fixa stylingen, det gör ditt arbete mer presentabelt


![Screenshot 2024-10-22 140935](https://github.com/user-attachments/assets/ea81ac05-3927-46a6-bcfa-360d50bef2e4)
![Screenshot 2024-10-22 141154](https://github.com/user-attachments/assets/f6faae85-6be0-400e-b9f2-b09bb329d14b)
![Screenshot 2024-10-22 141801](https://github.com/user-attachments/assets/fe99c42f-29bf-4395-a4de-92bba2893de3)
![Screenshot 2024-10-22 141926](https://github.com/user-attachments/assets/bd81bef4-fbc8-4feb-a47d-d2cc3a09da91)

2024-10-22 12:29 UTC, hhmbow requested changes
saknar navbar too

2024-10-23 08:15 UTC, PatrikHogblom approved these changes

2024-10-23 08:48 UTC, hhmbow approved these changes

2024-10-23 08:49 UTC, merged